FORMAT: 1A
HOST: http://spicar.io/

# SpiCar

This API is used for interaction with the SpiCar vehicle communication unit.

In case the API is used as JSON messages on PubNub, endpoint paths should be ignored.

All data can be requested manually. 
It is also possible to subscribe to data change events or periodic transmission of certain data. 
Please see under each data source whether event based or periodic updates are possible.
In all cases, the JSON format of the data responses are identical.

# Group Configuration
## Device Configuration

## Event Subscription [POST /events]

This message configures the device to automatically send JSON formatted data messages whenever a data value changes.

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + event
            + type (required, enum[string]) - Data to receive
                + Members
                    + `impact` - Time and severity of last detected impact
                    + `door_lock` - State of the vehicle door lock
                    + `door_1_open` - State of the first vehicle door
                    + `door_2_open` - State of the second vehicle door
                    + `door_3_open` - State of the third vehicle door
                    + `door_4_open` - State of the fourth vehicle door
                    + `door_5_open` - State of the fifth vehicle door
                    + `seat_1_free` - State of the first seat
                    + `seat_2_free` - State of the second seat
                    + `seat_3_free` - State of the third seat
                    + `seat_4_free` - State of the fourth seat
                    + `seat_5_free` - State of the fifth seat
                    + `drivetrain_state` - State of the drivetrain
                    + `window_1_open` - State of the first window
                    + `window_2_open` - State of the second window
                    + `window_3_open` - State of the third window
                    + `window_4_open` - State of the fourth window
                    + `handbrake_active` - State of the handbrake
                    + `gear_state` - Gear state (PRND)
            + enable (required, boolean)

+ Response 200 (application/json)
    + Attributes (object)
        + event
            + type (required, enum[string]) - Data to receive
                + Members
                    + `impact` - Time and severity of last detected impact
                    + `door_lock` - State of the vehicle door lock
                    + `door_1_open` - State of the first vehicle door
                    + `door_2_open` - State of the second vehicle door
                    + `door_3_open` - State of the third vehicle door
                    + `door_4_open` - State of the fourth vehicle door
                    + `door_5_open` - State of the fifth vehicle door
                    + `seat_1_free` - State of the first seat
                    + `seat_2_free` - State of the second seat
                    + `seat_3_free` - State of the third seat
                    + `seat_4_free` - State of the fourth seat
                    + `seat_5_free` - State of the fifth seat
                    + `drivetrain_state` - State of the drivetrain
                    + `window_1_open` - State of the first window
                    + `window_2_open` - State of the second window
                    + `window_3_open` - State of the third window
                    + `window_4_open` - State of the fourth window
                    + `handbrake_active` - State of the handbrake
                    + `gear_state` - Gear state (PRND)
            + result (required, boolean) - Result of subscription change
            + reason (optional, string) - Description of error
        

## Periodic Data Subscription [POST /periodic]

This message configures the device to automatically send JSON formatted data messages periodically, regardless of data value changes.

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + periodic
            + type (required, enum[string]) - Data to receive
                + Members
                    + `location` - GNSS and IMU sensor fusion based location data
                    + `lv_bat` - Low voltage battery state of charge
                    + `hv_bat` - High voltage battery state of charge. Only applicable for electrical vehicles
                    + `fuel` - Fuel level. Only applicable for internal combustion vehicles
                    + `door_lock` - State of the vehicle door lock
                    + `door_1_open` - State of the first vehicle door
                    + `door_2_open` - State of the second vehicle door
                    + `door_3_open` - State of the third vehicle door
                    + `door_4_open` - State of the fourth vehicle door
                    + `door_5_open` - State of the fifth vehicle door
                    + `seat_1_free` - State of the first seat
                    + `seat_2_free` - State of the second seat
                    + `seat_3_free` - State of the third seat
                    + `seat_4_free` - State of the fourth seat
                    + `seat_5_free` - State of the fifth seat
                    + `drivetrain_state` - State of the drivetrain
                    + `window_1_open` - State of the first window
                    + `window_2_open` - State of the second window
                    + `window_3_open` - State of the third window
                    + `window_4_open` - State of the fourth window
                    + `handbrake_active` - State of the handbrake
                    + `gear_state` - Gear state (PRND)
                    + `speed` - Speed as reported by the vehicle
                    + `rpm` - Engine RPM
            + interval (required, number) - Interval between messages, in seconds. 0 turns periodic messages for this data type off.

+ Response 200 (application/json)
    + Attributes (object)
        + event
            + type (required, enum[string]) - Data to receive
                + Members
                    + `location` - GNSS and IMU sensor fusion based location data
                    + `lv_bat` - Low voltage battery state of charge
                    + `hv_bat` - High voltage battery state of charge. Only applicable for electrical vehicles
                    + `fuel` - Fuel level. Only applicable for internal combustion vehicles
                    + `door_lock` - State of the vehicle door lock
                    + `door_1_open` - State of the first vehicle door
                    + `door_2_open` - State of the second vehicle door
                    + `door_3_open` - State of the third vehicle door
                    + `door_4_open` - State of the fourth vehicle door
                    + `door_5_open` - State of the fifth vehicle door
                    + `seat_1_free` - State of the first seat
                    + `seat_2_free` - State of the second seat
                    + `seat_3_free` - State of the third seat
                    + `seat_4_free` - State of the fourth seat
                    + `seat_5_free` - State of the fifth seat
                    + `drivetrain_state` - State of the drivetrain
                    + `window_1_open` - State of the first window
                    + `window_2_open` - State of the second window
                    + `window_3_open` - State of the third window
                    + `window_4_open` - State of the fourth window
                    + `handbrake_active` - State of the handbrake
                    + `gear_state` - Gear state (PRND)
                    + `speed` - Speed as reported by the vehicle
                    + `rpm` - Engine RPM
            + result (required, boolean) - Result of subscription change
            + reason (optional, string) - Description of error
        

# Group Requests

## Get [GET /get]

The get message retrieves current data values from the SpiCar unit.
For response format, please see the data section for the appropriate data type.

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get (required, enum[string]) - Data to receive
            + Members
                + `location` - GNSS and IMU sensor fusion based location data
                + `lv_bat` - Low voltage battery state of charge
                + `hv_bat` - High voltage battery state of charge. Only applicable for electrical vehicles
                + `fuel` - Fuel level. Only applicable for internal combustion vehicles
                + `impact` - Time and severity of last detected impact
                + `door_lock` - State of the vehicle door lock
                + `door_1_open` - State of the first vehicle door
                + `door_2_open` - State of the second vehicle door
                + `door_3_open` - State of the third vehicle door
                + `door_4_open` - State of the fourth vehicle door
                + `door_5_open` - State of the fifth vehicle door
                + `seat_1_free` - State of the first seat
                + `seat_2_free` - State of the second seat
                + `seat_3_free` - State of the third seat
                + `seat_4_free` - State of the fourth seat
                + `seat_5_free` - State of the fifth seat
                + `drivetrain_state` - State of the drivetrain
                + `window_1_open` - State of the first window
                + `window_2_open` - State of the second window
                + `window_3_open` - State of the third window
                + `window_4_open` - State of the fourth window
                + `handbrake_active` - State of the handbrake
                + `gear_state` - Gear state (PRND)
                + `speed` - Speed as reported by the vehicle
                + `rpm` - Engine RPM

+ Response 200 (application/json)
        
        For response format, please see the data section for the appropriate data type.

# Group Data

## Location [GET /location]

GNSS and IMU sensor fusion based location data.

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: location (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + location (required)
            + lat: 55.67594 (required, number) - Latitude of location (decimal degrees)
            + lon: 12.56553 (required, number) - Longitude of location (decimal degrees)
            + alt: 9.3 (required, number) - Altitude of location (meters above sea level)
            + heading: 223.48680 (required, number) - Magnetic heading (degrees)
            + speed: 10.2 (required, number) - Current speed (meters/second)

## LV Battery SoC [GET /lv_bat]

Low voltage battery state of charge in percent. 
The low voltage battery is often 12V in personal vehicles and 24V in trucks.

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: lv_bat (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + lv_bat (required)
            + soc: 65.8 (required, number) - Remaining battery power in percent

## HV Battery SoC [GET /hv_bat]

High voltage battery state of charge in percent.
Only applicable for electrical vehicles.

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: hv_bat (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + hv_bat (required)
            + soc: 65.8 (required, number) - Remaining battery power in percent

## Fuel Level [GET /fuel]

Fuel level. 
Only applicable for internal combustion vehicles.

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: fuel (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + fuel (required)
            + level: 65.8 (required, number) - Remaining fuel in liters

## Impact [GET /impact]

Time and severity of last detected impact.

Timestamp is in Unix time, which is seconds since Jan 01 1970 (UTC).

Events: Yes

Periodic: No

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: impact (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + impact (required)
            + time: 1492965666 (required, number) - Unix timestamp of impact.
            + force: 1.2 (required, number) - Force in g

## Door Lock [GET /door_lock]

Door lock status

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_lock (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_lock (required)
            + locked: true (required, boolean) - State of the vehicle door lock

## Door 1 State [GET /door_1_open]

State of the first vehicle door

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_1_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_1_open (required)
            + open: true (required, boolean) - State of the first vehicle door

## Door 2 State [GET /door_2_open]

State of the second vehicle door

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_2_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_2_open (required)
            + open: true (required, boolean) - State of the second vehicle door

## Door 3 State [GET /door_3_open]

State of the third vehicle door

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_3_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_3_open (required)
            + open: true (required, boolean) - State of the third vehicle door

## Door 4 State [GET /door_4_open]

State of the fourth vehicle door

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_4_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_4_open (required)
            + open: true (required, boolean) - State of the fourth vehicle door

## Door 5 State [GET /door_5_open]

State of the fifth vehicle door

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: door_5_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + door_5_open (required)
            + open: true (required, boolean) - State of the fifth vehicle door

## Seat 1 State [GET /seat_1_free]

State of the first seat

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: seat_1_free (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + seat_1_free (required)
            + free: true (required, boolean) - State of the first seat

## Seat 2 State [GET /seat_2_free]

State of the second seat

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: seat_2_free (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + seat_2_free (required)
            + free: true (required, boolean) - State of the second seat

## Seat 3 State [GET /seat_3_free]

State of the third seat

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: seat_3_free (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + seat_3_free (required)
            + free: true (required, boolean) - State of the third seat

## Seat 4 State [GET /seat_4_free]

State of the fourth seat

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: seat_4_free (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + seat_4_free (required)
            + free: true (required, boolean) - State of the fourth seat

## Seat 5 State [GET /seat_5_free]

State of the fifth seat

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: seat_5_free (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + seat_5_free (required)
            + free: true (required, boolean) - State of the fifth seat

## Drivetrain State [GET /drivetrain_state]

State of the drivetrain

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: drivetrain_state (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + drivetrain_state (required)
            + state (required, enum[string]) - State of the drivetrain
                + Members
                    + `off` - Vehicle and drivetrain is in power off mode
                    + `accessory` - Drivetrain is not powered, but accessories such as radio is
                    + `drive_enabled` - Drivetrain is powered and driving is possible depending on gear state

## Window 1 Position [GET /window_1_open]

State of the first window

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: window_1_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + window_1_open (required)
            + free: true (required, boolean) - State of the first window

## Window 2 Position [GET /window_2_open]

State of the second window

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: window_2_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + window_2_open (required)
            + free: true (required, boolean) - State of the second window

## Window 3 Position [GET /window_3_open]

State of the third window

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: window_3_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + window_3_open (required)
            + free: true (required, boolean) - State of the third window

## Window 4 Position [GET /window_4_open]

State of the fourth window

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: window_4_open (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + window_4_open (required)
            + free: true (required, boolean) - State of the fourth window

## Handbrake State [GET /handbrake_active]

State of the handbrake

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: handbrake_active (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + handbrake_active (required)
            + free: true (required, boolean) - State of the handbrake

## Gear State [GET /gear_state]

State of the gear

Events: Yes

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: gear_state (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + gear_state (required)
            + state (required, enum[string]) - State of the gear
                + Members
                    + `park` - Parking mode
                    + `reverse` - Reverse gear
                    + `neutral` - Neutral gear state
                    + `drive` - Only applicable for vehicles with automatic gears
                    + `1` - Only applicable for vehicles without automatic gears
                    + `2` - Only applicable for vehicles without automatic gears
                    + `3` - Only applicable for vehicles without automatic gears
                    + `4` - Only applicable for vehicles without automatic gears
                    + `5` - Only applicable for vehicles without automatic gears
                    + `6` - Only applicable for vehicles without automatic gears

## Vehicle Speed [GET /speed]

Speed as reported by the vehicle

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: speed (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + speed (required)
            + mps: 10.2 (required, number) - Current speed (meters/second), as reported by the vehicle

## Engine RPM [GET /rpm]

Engine revolutions per minute

Events: No

Periodic: Yes

+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (object)
        + get: rpm (required, string)

+ Response 200 (application/json)
    + Attributes (object)
        + rpm (required)
            + rpm: 7826 (required, number) - Engine revolutions per minute




# Group Aggregated Data